ALTER TABLE orders ADD COLUMN customer_action TEXT;
ALTER TABLE orders ADD COLUMN customer_action_reason TEXT;
ALTER TABLE orders ADD COLUMN customer_action_status TEXT NOT NULL DEFAULT 'none';
ALTER TABLE orders ADD COLUMN refund_status TEXT NOT NULL DEFAULT 'not_requested';
ALTER TABLE orders ADD COLUMN refund_amount INTEGER NOT NULL DEFAULT 0;
ALTER TABLE orders ADD COLUMN refund_account_title TEXT;
ALTER TABLE orders ADD COLUMN refund_account_number TEXT;
ALTER TABLE orders ADD COLUMN refund_bank_name TEXT;
ALTER TABLE orders ADD COLUMN refund_iban TEXT;
ALTER TABLE orders ADD COLUMN refund_phone TEXT;
ALTER TABLE orders ADD COLUMN refund_method TEXT;
ALTER TABLE orders ADD COLUMN refund_note TEXT;
ALTER TABLE orders ADD COLUMN refund_receipt_public_id TEXT;
ALTER TABLE orders ADD COLUMN refund_receipt_url TEXT;
ALTER TABLE orders ADD COLUMN refund_approved_at TEXT;
ALTER TABLE orders ADD COLUMN delivered_at TEXT;
CREATE INDEX IF NOT EXISTS idx_orders_customer_action ON orders(customer_action_status);
CREATE INDEX IF NOT EXISTS idx_orders_refund_status ON orders(refund_status);
CREATE INDEX IF NOT EXISTS idx_orders_delivered_at ON orders(delivered_at);
