name = "shano-shan-api"
main = "src/index.ts"
compatibility_date = "2026-09-22"

[[d1_databases]]
binding = "DB"
database_name = "shanoshan-d1-prod"
database_id = "f4a72919-838f-4442-b6d1-3c2568d9fd0e"
migrations_dir = "migrations"

[vars]
ALLOWED_ORIGINS = "http://localhost:5173,http://localhost:5174,https://www.shanoshan.com,https://admin.shanoshan.com,https://shanoshanfragrance-34ikk8xgx-ahmed-developer1.vercel.app"


[ai]
binding = "AI"
